"""Can a simple classifier tell a 'swapped' cat (generated by the dog->cat
OCE erasure model, prompted with 'a photo of dog') apart from a genuine
cat? Extracts CLIP image embeddings and fits a logistic regression probe,
run against two different genuine-control groups to check whether the
control's own model choice affects the conclusion:

  - control_A "airplane": genuine cat generated by the unrelated
    airplane->sky erasure model (cat/dog untouched by that edit)
  - control_B "baseline": genuine cat generated by fully unedited
    CompVis/stable-diffusion-v1-4 (no erasure at all), isolating the
    erasure edit as the only variable that differs from the swapped group
"""
import os
import csv
import numpy as np
import torch
from PIL import Image
from transformers import CLIPModel, CLIPProcessor
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

SWAPPED_DIR = "eval_cifar_full/dog/dog"  # "a photo of dog" through dog->cat model
CONTROLS = {
    "airplane": "eval_cifar_full/airplane/cat",         # genuine cat, unrelated edited model
    "baseline": "eval_cifar_full/baseline_unedited/cat",  # genuine cat, fully unedited SD1.4
}
SEED = 42

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").eval().to(device)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


@torch.no_grad()
def embed_folder(folder):
    files = sorted(f for f in os.listdir(folder) if f.endswith(".png"))
    embeds = []
    for fname in files:
        image = Image.open(os.path.join(folder, fname)).convert("RGB")
        inputs = processor(images=image, return_tensors="pt").to(device)
        feat = model.get_image_features(**inputs)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embeds.append(feat.squeeze(0).cpu().numpy())
    return np.stack(embeds), files


print("Embedding swapped (dog->cat) images...")
X_swap, files_swap = embed_folder(SWAPPED_DIR)

all_rows = []
for control_name, control_dir in CONTROLS.items():
    print(f"\n--- control: {control_name} ({control_dir}) ---")
    X_gen, files_gen = embed_folder(control_dir)

    X = np.concatenate([X_swap, X_gen], axis=0)
    y = np.array([1] * len(X_swap) + [0] * len(X_gen))  # 1 = swapped, 0 = genuine
    files = files_swap + files_gen
    groups = ["swapped"] * len(X_swap) + [f"genuine_{control_name}"] * len(X_gen)

    np.savez(f"erasure_detectability_embeddings_{control_name}.npz",
             X=X, y=y, files=np.array(files), groups=np.array(groups))
    print(f"Saved embeddings: X{X.shape} -> erasure_detectability_embeddings_{control_name}.npz")

    X_train, X_test, y_train, y_test, files_train, files_test = train_test_split(
        X, y, files, test_size=0.2, stratify=y, random_state=SEED
    )

    clf = LogisticRegression(max_iter=2000, C=1.0)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:  {acc*100:.2f}%")
    print(f"Precision: {prec*100:.2f}%")
    print(f"Recall:    {rec*100:.2f}%")
    print("Confusion matrix (rows=true, cols=pred), order=[genuine, swapped]:")
    print(cm)

    misclassified = []
    for fname, true_y, pred_y, prob in zip(files_test, y_test, y_pred, y_prob):
        if true_y != pred_y:
            label = "swapped" if true_y == 1 else "genuine"
            print(f"  MISS: {fname} (true={label}, pred_prob_swapped={prob:.3f})")
            misclassified.append(fname)

    all_rows.append({
        "control": control_name, "test_n": len(y_test),
        "accuracy": f"{acc*100:.2f}", "precision": f"{prec*100:.2f}", "recall": f"{rec*100:.2f}",
        "cm_genuine_genuine": cm[0][0], "cm_genuine_swapped": cm[0][1],
        "cm_swapped_genuine": cm[1][0], "cm_swapped_swapped": cm[1][1],
        "n_misclassified": len(misclassified),
    })

with open("erasure_detectability_results.csv", "w", newline="") as f:
    fieldnames = ["control", "test_n", "accuracy", "precision", "recall",
                  "cm_genuine_genuine", "cm_genuine_swapped",
                  "cm_swapped_genuine", "cm_swapped_swapped", "n_misclassified"]
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in all_rows:
        writer.writerow(row)

print("\nDONE")
