"""Can a simple classifier tell a 'swapped' cat (generated by the dog->cat
OCE erasure model, prompted with 'a photo of dog') apart from a 'genuine'
cat (generated by an unrelated erasure model, prompted with 'a photo of
cat')? Extracts CLIP image embeddings for both groups and fits a logistic
regression probe on top, reporting held-out accuracy/precision/recall/
confusion matrix.
"""
import os
import csv
import numpy as np
import torch
from PIL import Image
from transformers import CLIPModel, CLIPProcessor
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

SWAPPED_DIR = "eval_cifar_full/dog/dog"        # "a photo of dog" through dog->cat model
GENUINE_DIR = "eval_cifar_full/airplane/cat"   # "a photo of cat" through unrelated airplane model
SEED = 42

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").eval().to(device)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")


@torch.no_grad()
def embed_folder(folder):
    files = sorted(f for f in os.listdir(folder) if f.endswith(".png"))
    embeds = []
    for fname in files:
        image = Image.open(os.path.join(folder, fname)).convert("RGB")
        inputs = processor(images=image, return_tensors="pt").to(device)
        feat = model.get_image_features(**inputs)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embeds.append(feat.squeeze(0).cpu().numpy())
    return np.stack(embeds), files


print("Embedding swapped (dog->cat) images...")
X_swap, files_swap = embed_folder(SWAPPED_DIR)
print("Embedding genuine cat images...")
X_gen, files_gen = embed_folder(GENUINE_DIR)

X = np.concatenate([X_swap, X_gen], axis=0)
y = np.array([1] * len(X_swap) + [0] * len(X_gen))  # 1 = swapped, 0 = genuine
files = files_swap + files_gen
groups = ["swapped"] * len(X_swap) + ["genuine"] * len(X_gen)

np.savez("erasure_detectability_embeddings.npz",
         X=X, y=y, files=np.array(files), groups=np.array(groups))
print(f"Saved embeddings: X{X.shape}, y{y.shape} -> erasure_detectability_embeddings.npz")

X_train, X_test, y_train, y_test, files_train, files_test = train_test_split(
    X, y, files, test_size=0.2, stratify=y, random_state=SEED
)

clf = LogisticRegression(max_iter=2000, C=1.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_prob = clf.predict_proba(X_test)[:, 1]

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"\n=== Results (test set n={len(y_test)}) ===")
print(f"Accuracy:  {acc*100:.2f}%")
print(f"Precision: {prec*100:.2f}%")
print(f"Recall:    {rec*100:.2f}%")
print("Confusion matrix (rows=true, cols=pred), order=[genuine, swapped]:")
print(cm)

# misclassified examples
print("\n=== Misclassified test examples ===")
misclassified = []
for fname, true_y, pred_y, prob in zip(files_test, y_test, y_pred, y_prob):
    if true_y != pred_y:
        label = "swapped" if true_y == 1 else "genuine"
        print(f"  {fname} (true={label}, pred_prob_swapped={prob:.3f})")
        misclassified.append({"file": fname, "true": label, "pred_prob_swapped": f"{prob:.3f}"})

with open("erasure_detectability_results.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["metric", "value"])
    writer.writerow(["test_n", len(y_test)])
    writer.writerow(["accuracy", f"{acc*100:.2f}"])
    writer.writerow(["precision", f"{prec*100:.2f}"])
    writer.writerow(["recall", f"{rec*100:.2f}"])
    writer.writerow(["confusion_matrix_genuine_genuine", cm[0][0]])
    writer.writerow(["confusion_matrix_genuine_swapped", cm[0][1]])
    writer.writerow(["confusion_matrix_swapped_genuine", cm[1][0]])
    writer.writerow(["confusion_matrix_swapped_swapped", cm[1][1]])
    writer.writerow(["n_misclassified", len(misclassified)])

print("\nDONE")
